version: 2

models:
  - name: int_orders_enriched
    description: Orders enriched with customer and product information
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: order_total
        description: Total order value (price * quantity)
        tests:
          - not_null
      - name: order_profit
        description: Order profit (profit_per_unit * quantity)
